//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigestConfig) DeepCopyInto(out *DigestConfig) {
	*out = *in
	if in.AggregationWindow != nil {
		in, out := &in.AggregationWindow, &out.AggregationWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigestConfig.
func (in *DigestConfig) DeepCopy() *DigestConfig {
	if in == nil {
		return nil
	}
	out := new(DigestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfig) DeepCopyInto(out *EmailConfig) {
	*out = *in
	if in.StartTLS != nil {
		in, out := &in.StartTLS, &out.StartTLS
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfig.
func (in *EmailConfig) DeepCopy() *EmailConfig {
	if in == nil {
		return nil
	}
	out := new(EmailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfig.
func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfigList) DeepCopyInto(out *NotificationConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotificationConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfigList.
func (in *NotificationConfigList) DeepCopy() *NotificationConfigList {
	if in == nil {
		return nil
	}
	out := new(NotificationConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfigSpec) DeepCopyInto(out *NotificationConfigSpec) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(EmailConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EnabledCategories != nil {
		in, out := &in.EnabledCategories, &out.EnabledCategories
		*out = make([]Category, len(*in))
		copy(*out, *in)
	}
	if in.EnabledChannels != nil {
		in, out := &in.EnabledChannels, &out.EnabledChannels
		*out = make([]Channel, len(*in))
		copy(*out, *in)
	}
	if in.UsernameIsEmail != nil {
		in, out := &in.UsernameIsEmail, &out.UsernameIsEmail
		*out = new(bool)
		**out = **in
	}
	if in.NewVersionDigest != nil {
		in, out := &in.NewVersionDigest, &out.NewVersionDigest
		*out = new(DigestConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RecordRetention != nil {
		in, out := &in.RecordRetention, &out.RecordRetention
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfigSpec.
func (in *NotificationConfigSpec) DeepCopy() *NotificationConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfigStatus) DeepCopyInto(out *NotificationConfigStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfigStatus.
func (in *NotificationConfigStatus) DeepCopy() *NotificationConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NotificationConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationPreferences) DeepCopyInto(out *NotificationPreferences) {
	*out = *in
	if in.OptOutCategories != nil {
		in, out := &in.OptOutCategories, &out.OptOutCategories
		*out = make([]Category, len(*in))
		copy(*out, *in)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]Channel, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationPreferences.
func (in *NotificationPreferences) DeepCopy() *NotificationPreferences {
	if in == nil {
		return nil
	}
	out := new(NotificationPreferences)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRecord) DeepCopyInto(out *NotificationRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecord.
func (in *NotificationRecord) DeepCopy() *NotificationRecord {
	if in == nil {
		return nil
	}
	out := new(NotificationRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRecordList) DeepCopyInto(out *NotificationRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotificationRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecordList.
func (in *NotificationRecordList) DeepCopy() *NotificationRecordList {
	if in == nil {
		return nil
	}
	out := new(NotificationRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRecordSpec) DeepCopyInto(out *NotificationRecordSpec) {
	*out = *in
	out.Recipient = in.Recipient
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecordSpec.
func (in *NotificationRecordSpec) DeepCopy() *NotificationRecordSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRecordStatus) DeepCopyInto(out *NotificationRecordStatus) {
	*out = *in
	if in.SentAt != nil {
		in, out := &in.SentAt, &out.SentAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecordStatus.
func (in *NotificationRecordStatus) DeepCopy() *NotificationRecordStatus {
	if in == nil {
		return nil
	}
	out := new(NotificationRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subject) DeepCopyInto(out *Subject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subject.
func (in *Subject) DeepCopy() *Subject {
	if in == nil {
		return nil
	}
	out := new(Subject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserProfile) DeepCopyInto(out *UserProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserProfile.
func (in *UserProfile) DeepCopy() *UserProfile {
	if in == nil {
		return nil
	}
	out := new(UserProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserProfileList) DeepCopyInto(out *UserProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserProfileList.
func (in *UserProfileList) DeepCopy() *UserProfileList {
	if in == nil {
		return nil
	}
	out := new(UserProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserProfileSpec) DeepCopyInto(out *UserProfileSpec) {
	*out = *in
	out.Subject = in.Subject
	in.Preferences.DeepCopyInto(&out.Preferences)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserProfileSpec.
func (in *UserProfileSpec) DeepCopy() *UserProfileSpec {
	if in == nil {
		return nil
	}
	out := new(UserProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserProfileStatus) DeepCopyInto(out *UserProfileStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	if in.FirstSeen != nil {
		in, out := &in.FirstSeen, &out.FirstSeen
		*out = (*in).DeepCopy()
	}
	if in.EnablementSentAt != nil {
		in, out := &in.EnablementSentAt, &out.EnablementSentAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserProfileStatus.
func (in *UserProfileStatus) DeepCopy() *UserProfileStatus {
	if in == nil {
		return nil
	}
	out := new(UserProfileStatus)
	in.DeepCopyInto(out)
	return out
}
